### PR TITLE
Added a space before the button label

### PR DESCRIPTION
**Pull request by zvirja**
Space is missed between button icon and label. I've added it.

### CODE REVIEW

**Comment by jamesgarfield** [comment]
Thanks!

**Comment by zvirja** [comment]
You are welcome.

Don't forget to increase version to trigger script update :)

**Comment by jamesgarfield** [comment]
Ha! Good point :-)

Did you install from github or did you find this on one of the various
UserScript aggregation sites?

**Comment by zvirja** [comment]
I've googled it directly by _github clone source tree userscript_ query and installed it from the GitHub direclty.

BTW, you can close the [same change request](https://openuserjs.org/scripts/jgarf/GitHubSourceTree/issues/Use_space_between_icon_and_text) on one of sites.

**Comment by jamesgarfield** [comment]
3 helps in one! I'll have to look ay my settings in OpenUserJS to see if
there's a way to get notified about issues like that.

Thanks for taking an interest.

**Comment by jerone** [comment]
Great PR. What about changing the icon to `octicon-desktop-download`, the same as GitHub Desktop?
2015-09-29 20_55_06-openuserjs_openuserjs org

> settings in OpenUserJS to see if there's a way to get notified about issues like that.

That's not possible right now, but you could open an issue for that: https://github.com/OpenUserJs/OpenUserJS.org

**Pull request merged**
